# ==============================================================================
# INSTRUÇÕES PARA O WORKSHOP - SIGA OS 2 PASSOS ABAIXO:
# ==============================================================================

# PASSO 1: DAR UM NOME ÚNICO AO SEU CAMINHO/SITE
#   - Pressione 'Ctrl+H' para abrir "Localizar e Substituir".
#   - No campo "Localizar", digite: site-pedroteixeira
#   - No campo "Substituir", digite um nome único para você (ex: pedro-teixeira).
#   - Clique em "Substituir Todos".

# PASSO 2: ALTERAR A SUA MENSAGEM
#   - Encontre a linha que começa com "value:" e altere a mensagem.
# ==============================================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-pedroteixeira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site-pedroteixeira
  template:
    metadata:
      labels:
        app: site-pedroteixeira
    spec:
      containers:
      - name: web
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
        env:
        - name: HELLO_TEXT
          value: "Bem-vindo ao Workshop de Kubernetes! Site do Pedro Teixeira"
---
apiVersion: v1
kind: Service
metadata:
  name: site-pedroteixeira-service
spec:
  type: ClusterIP
  selector:
    app: site-pedroteixeira
  ports:
  - port: 80
    targetPort: 80
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: site-pedroteixeira-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /site-pedroteixeira
        pathType: Prefix
        backend:
          service:
            name: site-pedroteixeira-service
            port:
              number: 80
