# Este é o modelo para criar seu site no Kubernetes.
# O participante só precisa se preocupar em alterar a MENSAGEM.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meu-site
  template:
    metadata:
      labels:
        app: meu-site
    spec:
      containers:
      - name: web
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
        env:
        - name: HELLO_TEXT
          # ================================================================ #
          # >> ÚNICA LINHA PARA ALTERAR <<
          # Troque a frase abaixo pela sua mensagem personalizada!
          value: "Bem-vindo ao Workshop de Kubernetes! Pedro Teixeira"
          # ================================================================ #
---
apiVersion: v1
kind: Service
metadata:
  name: meu-servico
spec:
  type: NodePort
  selector:
    app: meu-site
  ports:
  - port: 80
    targetPort: 80
